name: Lint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy
    - name: Analysing the code with pylint + mypy
      run: |
        pylint `ls -R|grep .py$|xargs`
        mypy `ls -R|grep .py$|xargs`
